In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.0


In [3]:
scaler = tf.constant(8)
print(scaler.ndim)

0


In [7]:
vector = tf.constant([10,2,0,40] , dtype=tf.float32)
print(vector)
print(vector.ndim)

tf.Tensor([10.  2.  0. 40.], shape=(4,), dtype=float32)
1


In [10]:
matrix = tf.constant([[10,20,30] , [10,20,60]] , dtype = tf.float32)
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10. 20. 30.]
 [10. 20. 60.]], shape=(2, 3), dtype=float32)
2
